import { paths } from "@routes/paths";
import {
  FiHome,
  FiPieChart,
  FiUsers,
  FiCalendar,
  FiSettings,
  FiLogOut,
} from "react-icons/fi";
import { MdDashboard } from "react-icons/md";



export const featuredProperties = [
  {
    id: "f1",
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914",
    title: "Luxury Villa in Banana Island",
    price: "$2,500,000",
    location: "Banana Island, Lagos",
  },
  {
    id: "f2",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    title: "Modern Apartment in Ikoyi",
    price: "$850,000",
    location: "Ikoyi, Lagos",
  },
];

export const recentlyViewed = [
  {
    id: "r1",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    title: "Waterfront Property in Lekki",
    price: "$1,200,000",
    location: "Lekki Phase 1, Lagos",
  },
];

// Hardcoded dummy data
export const stats = {
  totalListings: 24,
  activeLeads: 18,
  commission: 12450,
  closedDeals: 2,
};

export const performanceData = [
  { month: "Jan", views: 120, clicks: 65 },
  { month: "Feb", views: 190, clicks: 45 },
  { month: "Mar", views: 300, clicks: 25 },
  { month: "Apr", views: 250, clicks: 35 },
  { month: "May", views: 180, clicks: 25 },
];

export const leadSources = [
  { source: "Website", percentage: 45, color: "#28B16D" },
  { source: "Social Media", percentage: 25, color: "#122947" },
  { source: "Referrals", percentage: 20, color: "#EE6002" },
  { source: "Direct", percentage: 10, color: "#8E9395" },
];

export const propertiess = [
  {
    id: 1,
    title: "Luxury Villa",
    status: "active",
    price: "$1,200,000",
    location: "Beverly Hills, CA",
    beds: 5,
    baths: 4,
    area: "3,500 sqft",
    views: 245,
    inquiries: 12,
    slug: "new-property-01",
    image:
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
  },
  {
    id: 2,
    title: "Downtown Apartment",
    status: "pending",
    price: "$750,000",
    location: "New York, NY",
    beds: 2,
    baths: 2,
    area: "1,200 sqft",
    views: 189,
    inquiries: 8,
    slug: "another-new-property",
    image:
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
  },
];

export const leads = [
  {
    id: 1,
    name: "Sarah Johnson",
    email: "sarah@example.com",
    phone: "(555) 123-4567",
    property: "Luxury Villa",
    status: "New",
    lastContact: "2 hours ago",
  },
  {
    id: 2,
    name: "Michael Chen",
    email: "michael@example.com",
    phone: "(555) 987-6543",
    property: "Downtown Apartment",
    status: "Follow-up",
    lastContact: "1 day ago",
  },
];

export const appointments = [
  {
    id: 1,
    client: "David Wilson",
    property: "Luxury Villa",
    date: "May 15, 2023",
    time: "2:00 PM",
    type: "In-person",
  },
  {
    id: 2,
    client: "Emily Rodriguez",
    property: "Downtown Apartment",
    date: "May 16, 2023",
    time: "11:00 AM",
    type: "Virtual",
  },
];

// export const DashBoardMenuItems = [
//   {
//     title: "Dashboard",
//     icon: MdDashboard,
//     link: `${paths.admin}/dashboard`,
//     visibility: ["admin"],
//   },
//   {
//     title: "Dashboard",
//     icon: MdDashboard,
//     link: `${paths.agent}/dashboard`,
//     visibility: ["realtor"],
//   },
//   {
//     title: "Dashboard",
//     icon: MdDashboard,
//     link: `${paths.otherUsers}/dashboard`,
//     visibility: ["engineer", "service", "trader"],
//   },
//   {
//     title: "My Properties",
//     icon: FiHome,
//     link: `${paths.agent}/properties`,
//     visibility: ["realtor"],
//   },
//   {
//     title: "Leads & Inquiries",
//     icon: FiUsers,
//     link: `${paths.sharedRoute}/lead&inquiries`,
//     visibility: ["admin", "realtor", "engineer", "service", "trader"],
//   },
//   {
//     title: "Analytics",
//     icon: FiPieChart,
//     link: `${paths.sharedRoute}/analytics`,
//     visibility: ["admin", "realtor", "engineer", "service", "trader"],
//   },
//   {
//     title: "Schedule",
//     icon: FiCalendar,
//     link: `${paths.sharedRoute}/schedule`,
//     visibility: [ "realtor", "engineer", "service", "trader"],
//   },
//   {
//     title: "Settings",
//     icon: FiSettings,
//     link: `${paths.generalRoute}/settings`,
//     visibility: ["admin", "realtor", "engineer", "service", "trader"],
//   },
//   {
//     title: "Logout",
//     icon: FiLogOut,
//     link: `${paths.sharedRoute}/settings`,
//     visibility: ["admin", "realtor", "engineer", "service", "trader"],
//   },
// ];


// import { 
//   MdDashboard, 
//   FiHome, 
//   FiUsers, 
//   FiPieChart, 
//   FiCalendar, 
//   FiSettings, 
//   FiLogOut 
// } from "react-icons/fi";

export const DashBoardMenuItems = [
  {
    title: "Dashboard",
    icon: MdDashboard,
    link: `${paths.admin}/dashboard`,
    visibility: ["admin"],
  },
  {
    title: "Dashboard",
    icon: MdDashboard,
    link: `${paths.agent}/dashboard`,
    visibility: ["realtor"],
  },
  {
    title: "Dashboard",
    icon: MdDashboard,
    link: `${paths.otherUsers}/dashboard`,
    visibility: ["engineer", "service", "trader"],
  },
  {
    title: "My Properties",
    icon: FiHome,
    link: `${paths.agent}/properties/all`, // Main link (optional)
    visibility: ["realtor"],
    submenu: [
      {
        title: "All Properties",
        link: `${paths.agent}/properties/all`,
      },
      {
        title: "Add New Property",
        link: `${paths.agent}/properties/add`,
      },
      {
        title: "Boost Listings",
        link: `#`,
      },
    ],
  },
  {
    title: "Leads & Inquiries",
    icon: FiUsers,
    link: `${paths.generalRoute}/lead&inquiries`,
    visibility: ["admin", "realtor", "engineer", "service", "trader"],
     submenu: [
      {
        title: "New Leads",
        link: `#`,
      },
      {
        title: "Messages",
        link: `#`,
      },
      {
        title: "Boost Listings",
        link: `#`,
      },
        {
    title: "Schedule",
    link: `${paths.generalRoute}/schedule`,

  },
    ],
  },
  {
    title: "Analytics",
    icon: FiPieChart,
    link: `${paths.sharedRoute}/analytics`,
    visibility: ["admin", "realtor", "engineer", "service", "trader"],
  },

  {
    title: "Settings",
    icon: FiSettings,
    link: `${paths.generalRoute}/settings`,
    visibility: ["admin", "realtor", "engineer", "service", "trader"],
  },
  {
    title: "Logout",
    icon: FiLogOut,
    link: `${paths.sharedRoute}/settings`,
    visibility: ["admin", "realtor", "engineer", "service", "trader"],
  },
];



export const NigerianStates = [
  {
    state: "Abia",
    lgas: [
      "Aba North",
      "Aba South",
      "Arochukwu",
      "Bende",
      "Ikwuano",
      "Isiala Ngwa North",
      "Isiala Ngwa South",
      "Isuikwuato",
      "Obi Ngwa",
      "Ohafia",
      "Osisioma",
      "Ugwunagbo",
      "Ukwa East",
      "Ukwa West",
      "Umuahia North",
      "Umuahia South",
      "Umu Nneochi",
    ],
  },

  {
    state: "Adamawa",
    lgas: [
      "Demsa",
      "Fufure",
      "Ganye",
      "Gayuk",
      "Girei",
      "Gombi",
      "Hong",
      "Jada",
      "Lamurde",
      "Madagali",
      "Maiha",
      "Mayo Belwa",
      "Michika",
      "Mubi North",
      "Mubi South",
      "Numan",
      "Shelleng",
      "Song",
      "Toungo",
      "Yola North",
      "Yola South",
    ],
  },
  {
    state: "Akwa Ibom",
    lgas: [
      "Abak",
      "Eastern Obolo",
      "Eket",
      "Esit Eket",
      "Essien Udim",
      "Etim Ekpo",
      "Etinan",
      "Ibeno",
      "Ibesikpo Asutan",
      "Ibiono-Ibom",
      "Ika",
      "Ikono",
      "Ikot Abasi",
      "Ikot Ekpene",
      "Ini",
      "Itu",
      "Mbo",
      "Mkpat-Enin",
      "Nsit-Atai",
      "Nsit-Ibom",
      "Nsit-Ubium",
      "Obot Akara",
      "Okobo",
      "Onna",
      "Oron",
      "Oruk Anam",
      "Udung-Uko",
      "Ukanafun",
      "Uruan",
      "Urue-Offong/Oruko",
      "Uyo",
    ],
  },
  {
    state: "Anambra",
    lgas: [
      "Aguata",
      "Anambra East",
      "Anambra West",
      "Anaocha",
      "Awka North",
      "Awka South",
      "Ayamelum",
      "Dunukofia",
      "Ekwusigo",
      "Idemili North",
      "Idemili South",
      "Ihiala",
      "Njikoka",
      "Nnewi North",
      "Nnewi South",
      "Ogbaru",
      "Onitsha North",
      "Onitsha South",
      "Orumba North",
      "Orumba South",
      "Oyi",
    ],
  },
  {
    state: "Bauchi",
    lgas: [
      "Alkaleri",
      "Bauchi",
      "Bogoro",
      "Damban",
      "Darazo",
      "Dass",
      "Gamawa",
      "Ganjuwa",
      "Giade",
      "Itas/Gadau",
      "Jama are",
      "Katagum",
      "Kirfi",
      "Misau",
      "Ningi",
      "Shira",
      "Tafawa Balewa",
      "Toro",
      "Warji",
      "Zaki",
    ],
  },
  {
    state: "Benue",
    lgas: [
      "Ado",
      "Agatu",
      "Apa",
      "Buruku",
      "Gboko",
      "Guma",
      "Gwer East",
      "Gwer West",
      "Katsina-Ala",
      "Konshisha",
      "Kwande",
      "Logo",
      "Makurdi",
      "Obi",
      "Ogbadibo",
      "Ohimini",
      "Oju",
      "Okpokwu",
      "Oturkpo",
      "Tarka",
      "Ukum",
      "Ushongo",
      "Vandeikya",
    ],
  },
  {
    state: "Borno",
    lgas: [
      "Abadam",
      "Askira/Uba",
      "Bama",
      "Bayo",
      "Biu",
      "Chibok",
      "Damboa",
      "Dikwa",
      "Gubio",
      "Guzamala",
      "Gwoza",
      "Hawul",
      "Jere",
      "Kaga",
      "Kala/Balge",
      "Konduga",
      "Kukawa",
      "Kwaya Kusar",
      "Mafa",
      "Magumeri",
      "Maiduguri",
      "Marte",
      "Mobbar",
      "Monguno",
      "Ngala",
      "Nganzai",
      "Shani",
    ],
  },
  {
    state: "Bayelsa",
    lgas: [
      "Brass",
      "Ekeremor",
      "Kolokuma/Opokuma",
      "Nembe",
      "Ogbia",
      "Sagbama",
      "Southern Ijaw",
      "Yenagoa",
    ],
  },
  {
    state: "Cross River",
    lgas: [
      "Abi",
      "Akamkpa",
      "Akpabuyo",
      "Bakassi",
      "Bekwarra",
      "Biase",
      "Boki",
      "Calabar Municipal",
      "Calabar South",
      "Etung",
      "Ikom",
      "Obanliku",
      "Obubra",
      "Obudu",
      "Odukpani",
      "Ogoja",
      "Yakurr",
      "Yala",
    ],
  },
  {
    state: "Delta",
    lgas: [
      "Aniocha North",
      "Aniocha South",
      "Bomadi",
      "Burutu",
      "Ethiope East",
      "Ethiope West",
      "Ika North East",
      "Ika South",
      "Isoko North",
      "Isoko South",
      "Ndokwa East",
      "Ndokwa West",
      "Okpe",
      "Oshimili North",
      "Oshimili South",
      "Patani",
      "Sapele",
      "Udu",
      "Ughelli North",
      "Ughelli South",
      "Ukwuani",
      "Uvwie",
      "Warri North",
      "Warri South",
      "Warri South West",
    ],
  },
  {
    state: "Ebonyi",
    lgas: [
      "Abakaliki",
      "Afikpo North",
      "Afikpo South (Edda)",
      "Ebonyi",
      "Ezza North",
      "Ezza South",
      "Ikwo",
      "Ishielu",
      "Ivo",
      "Izzi",
      "Ohaozara",
      "Ohaukwu",
      "Onicha",
    ],
  },
  {
    state: "Edo",
    lgas: [
      "Akoko-Edo",
      "Egor",
      "Esan Central",
      "Esan North-East",
      "Esan South-East",
      "Esan West",
      "Etsako Central",
      "Etsako East",
      "Etsako West",
      "Igueben",
      "Ikpoba Okha",
      "Orhionmwon",
      "Oredo",
      "Ovia North-East",
      "Ovia South-West",
      "Owan East",
      "Owan West",
      "Uhunmwonde",
    ],
  },
  {
    state: "Ekiti",
    lgas: [
      "Ado Ekiti",
      "Efon",
      "Ekiti East",
      "Ekiti South-West",
      "Ekiti West",
      "Emure",
      "Gbonyin",
      "Ido Osi",
      "Ijero",
      "Ikere",
      "Ikole",
      "Ilejemeje",
      "Irepodun/Ifelodun",
      "Ise/Orun",
      "Moba",
      "Oye",
    ],
  },
  {
    state: "Enugu",
    lgas: [
      "Aninri",
      "Awgu",
      "Enugu East",
      "Enugu North",
      "Enugu South",
      "Ezeagu",
      "Igbo Etiti",
      "Igbo Eze North",
      "Igbo Eze South",
      "Isi Uzo",
      "Nkanu East",
      "Nkanu West",
      "Nsukka",
      "Oji River",
      "Udenu",
      "Udi",
      "Uzo-Uwani",
    ],
  },
  {
    state: "FCT",
    lgas: [
      "Abaji",
      "Abuja Municipal Area Council",
      "Bwari",
      "Gwagwalada",
      "Kuje",
      "Kwali",
    ],
  },
  {
    state: "Gombe",
    lgas: [
      "Akko",
      "Balanga",
      "Billiri",
      "Dukku",
      "Funakaye",
      "Gombe",
      "Kaltungo",
      "Kwami",
      "Nafada",
      "Shongom",
      "Yamaltu/Deba",
    ],
  },
  {
    state: "Imo",
    lgas: [
      "Aboh Mbaise",
      "Ahiazu Mbaise",
      "Ehime Mbano",
      "Ezinihitte",
      "Ideato North",
      "Ideato South",
      "Ihitte/Uboma",
      "Ikeduru",
      "Isiala Mbano",
      "Isu",
      "Mbaitoli",
      "Ngor Okpala",
      "Njaba",
      "Nkwerre",
      "Nwangele",
      "Obowo",
      "Oguta",
      "Ohaji/Egbema",
      "Okigwe",
      "Orlu",
      "Orsu",
      "Oru East",
      "Oru West",
      "Owerri Municipal",
      "Owerri North",
      "Owerri West",
      "Unuimo",
    ],
  },
  {
    state: "Jigawa",
    lgas: [
      "Auyo",
      "Babura",
      "Biriniwa",
      "Birnin Kudu",
      "Buji",
      "Dutse",
      "Gagarawa",
      "Garki",
      "Gumel",
      "Guri",
      "Gwaram",
      "Gwiwa",
      "Hadejia",
      "Jahun",
      "Kafin Hausa",
      "Kaugama",
      "Kazaure",
      "Kiri Kasama",
      "Kiyawa",
      "Maigatari",
      "Malam Madori",
      "Miga",
      "Ringim",
      "Roni",
      "Sule Tankarkar",
      "Taura",
      "Yankwashi",
    ],
  },
  {
    state: "Kebbi",
    lgas: [
      "Aleiro",
      "Arewa",
      "Argungu",
      "Augie",
      "Bagudo",
      "Birnin Kebbi",
      "Bunza",
      "Dandi",
      "Fakai",
      "Gwandu",
      "Jega",
      "Kalgo",
      "Koko/Besse",
      "Maiyama",
      "Ngaski",
      "Sakaba",
      "Shanga",
      "Suru",
      "Danko-Wasagu",
      "Yauri",
      "Zuru",
    ],
  },
  {
    state: "Kaduna",
    lgas: [
      "Birnin Gwari",
      "Chikun",
      "Giwa",
      "Igabi",
      "Ikara",
      "Jaba",
      "Jema a",
      "Kachia",
      "Kaduna North",
      "Kaduna South",
      "Kagarko",
      "Kajuru",
      "Kaura",
      "Kauru",
      "Kubau",
      "Kudan",
      "Lere",
      "Makarfi",
      "Sabon Gari",
      "Sanga",
      "Soba",
      "Zangon Kataf",
      "Zaria",
    ],
  },
  {
    state: "Kano",
    lgas: [
      "Ajingi",
      "Albasu",
      "Bagwai",
      "Bebeji",
      "Bichi",
      "Bunkure",
      "Dala",
      "Dambatta",
      "Dawakin Kudu",
      "Dawakin Tofa",
      "Doguwa",
      "Fagge",
      "Gabasawa",
      "Garko",
      "Garun Mallam",
      "Gaya",
      "Gezawa",
      "Gwale",
      "Gwarzo",
      "Kabo",
      "Kano Municipal",
      "Karaye",
      "Kibiya",
      "Kiru",
      "Kumbotso",
      "Kunchi",
      "Kura",
      "Madobi",
      "Makoda",
      "Minjibir",
      "Nasarawa",
      "Rano",
      "Rimin Gado",
      "Rogo",
      "Shanono",
      "Sumaila",
      "Takai",
      "Tarauni",
      "Tofa",
      "Tsanyawa",
      "Tudun Wada",
      "Ungogo",
      "Warawa",
      "Wudil",
    ],
  },
  {
    state: "Kogi",
    lgas: [
      "Adavi",
      "Ajaokuta",
      "Ankpa",
      "Bassa",
      "Dekina",
      "Ibaji",
      "Idah",
      "Igalamela Odolu",
      "Ijumu",
      "Kabba/Bunu",
      "Kogi",
      "Lokoja",
      "Mopa Muro",
      "Ofu",
      "Ogori/Magongo",
      "Okehi",
      "Okene",
      "Olamaboro",
      "Omala",
      "Yagba East",
      "Yagba West",
    ],
  },
  {
    state: "Katsina",
    lgas: [
      "Bakori",
      "Batagarawa",
      "Batsari",
      "Baure",
      "Bindawa",
      "Charanchi",
      "Dandume",
      "Danja",
      "Dan Musa",
      "Daura",
      "Dutsi",
      "Dutsin Ma",
      "Faskari",
      "Funtua",
      "Ingawa",
      "Jibia",
      "Kafur",
      "Kaita",
      "Kankara",
      "Kankia",
      "Katsina",
      "Kurfi",
      "Kusada",
      "Mai Adua",
      "Malumfashi",
      "Mani",
      "Mashi",
      "Matazu",
      "Musawa",
      "Rimi",
      "Sabuwa",
      "Safana",
      "Sandamu",
      "Zango",
    ],
  },
  {
    state: "Kwara",
    lgas: [
      "Asa",
      "Baruten",
      "Edu",
      "Ekiti",
      "Ifelodun",
      "Ilorin East",
      "Ilorin South",
      "Ilorin West",
      "Irepodun",
      "Isin",
      "Kaiama",
      "Moro",
      "Offa",
      "Oke Ero",
      "Oyun",
      "Pategi",
    ],
  },
  {
    state: "Lagos",
    lgas: [
      "Agege",
      "Ajeromi-Ifelodun",
      "Alimosho",
      "Amuwo-Odofin",
      "Apapa",
      "Badagry",
      "Epe",
      "Eti Osa",
      "Ibeju-Lekki",
      "Ifako-Ijaiye",
      "Ikeja",
      "Ikorodu",
      "Kosofe",
      "Lagos Island",
      "Lagos Mainland",
      "Mushin",
      "Ojo",
      "Oshodi-Isolo",
      "Shomolu",
      "Surulere",
    ],
  },
  {
    state: "Nasarawa",
    lgas: [
      "Akwanga",
      "Awe",
      "Doma",
      "Karu",
      "Keana",
      "Keffi",
      "Kokona",
      "Lafia",
      "Nasarawa",
      "Nasarawa Egon",
      "Obi",
      "Toto",
      "Wamba",
    ],
  },
  {
    state: "Niger",
    lgas: [
      "Agaie",
      "Agwara",
      "Bida",
      "Borgu",
      "Bosso",
      "Chanchaga",
      "Edati",
      "Gbako",
      "Gurara",
      "Katcha",
      "Kontagora",
      "Lapai",
      "Lavun",
      "Magama",
      "Mariga",
      "Mashegu",
      "Mokwa",
      "Moya",
      "Paikoro",
      "Rafi",
      "Rijau",
      "Shiroro",
      "Suleja",
      "Tafa",
      "Wushishi",
    ],
  },
  {
    state: "Ogun",
    lgas: [
      "Abeokuta North",
      "Abeokuta South",
      "Ado-Odo/Ota",
      "Ewekoro",
      "Ifo",
      "Ijebu East",
      "Ijebu North",
      "Ijebu North East",
      "Ijebu Ode",
      "Ikenne",
      "Imeko Afon",
      "Ipokia",
      "Obafemi Owode",
      "Odeda",
      "Odogbolu",
      "Ogun Waterside",
      "Remo North",
      "Shagamu",
      "Yewa North",
      "Yewa South",
    ],
  },
  {
    state: "Ondo",
    lgas: [
      "Akoko North-East",
      "Akoko North-West",
      "Akoko South-East",
      "Akoko South-West",
      "Akure North",
      "Akure South",
      "Ese Odo",
      "Idanre",
      "Ifedore",
      "Ilaje",
      "Ile Oluji/Okeigbo",
      "Irele",
      "Odigbo",
      "Okitipupa",
      "Ondo East",
      "Ondo West",
      "Ose",
      "Owo",
    ],
  },
  {
    state: "Osun",
    lgas: [
      "Aiyedaade",
      "Aiyedire",
      "Atakunmosa East",
      "Atakunmosa West",
      "Boluwaduro",
      "Boripe",
      "Ede North",
      "Ede South",
      "Egbedore",
      "Ejigbo",
      "Ife Central",
      "Ife East",
      "Ife North",
      "Ife South",
      "Ifedayo",
      "Ifelodun",
      "Ila",
      "Ilesa East",
      "Ilesa West",
      "Irepodun",
      "Irewole",
      "Isokan",
      "Iwo",
      "Obokun",
      "Odo Otin",
      "Ola Oluwa",
      "Olorunda",
      "Oriade",
      "Orolu",
      "Osogbo",
    ],
  },
  {
    state: "Oyo",
    lgas: [
      "Afijio",
      "Akinyele",
      "Atiba",
      "Atisbo",
      "Egbeda",
      "Ibadan North",
      "Ibadan North-East",
      "Ibadan North-West",
      "Ibadan South - East",
      "Ibadan South-West",
      "Ibarapa Central",
      "Ibarapa East",
      "Ibarapa North",
      "Ido",
      "Irepo",
      "Iseyin",
      "Itesiwaju",
      "Iwajowa",
      "Kajola",
      "Lagelu",
      "Ogbomosho North",
      "Ogbomosho South",
      "Ogo Oluwa",
      "Olorunsogo",
      "Oluyole",
      "Ona Ara",
      "Orelope",
      "Ori Ire",
      "Oyo East",
      "Oyo West",
      "Saki East",
      "Saki West",
      "Surulere",
    ],
  },
  {
    state: "Plateau",
    lgas: [
      "Bokkos",
      "Barkin Ladi",
      "Bassa",
      "Jos East",
      "Jos North",
      "Jos South",
      "Kanam",
      "Kanke",
      "Langtang North",
      "Langtang South",
      "Mangu",
      "Mikang",
      "Pankshin",
      "Qua'an Pan",
      "Riyom",
      "Shendam",
      "Wase",
    ],
  },
  {
    state: "Rivers",
    lgas: [
      "Abua/Odual",
      "Ahoada East",
      "Ahoada West",
      "Akuku-Toru",
      "Andoni",
      "Asari-Toru",
      "Bonny",
      "Degema",
      "Eleme",
      "Emuoha",
      "Etche",
      "Gokana",
      "Ikwerre",
      "Khana",
      "Obio/Akpor",
      "Ogba/Egbema/Ndoni",
      "Ogu/Bolo",
      "Okrika",
      "Omuma",
      "Opobo/Nkoro",
      "Oyigbo",
      "Port Harcourt",
      "Tai",
    ],
  },
  {
    state: "Sokoto",
    lgas: [
      "Binji",
      "Bodinga",
      "Dange Shuni",
      "Gada",
      "Goronyo",
      "Gudu",
      "Gwadabawa",
      "Illela",
      "Isa",
      "Kebbe",
      "Kware",
      "Rabah",
      "Sabon Birni",
      "Shagari",
      "Silame",
      "Sokoto North",
      "Sokoto South",
      "Tambuwal",
      "Tangaza",
      "Tureta",
      "Wamako",
      "Wurno",
      "Yabo",
    ],
  },
  {
    state: "Taraba",
    lgas: [
      "Ardo Kola",
      "Bali",
      "Donga",
      "Gashaka",
      "Gassol",
      "Ibi",
      "Jalingo",
      "Karim Lamido",
      "Kumi",
      "Lau",
      "Sardauna",
      "Takum",
      "Ussa",
      "Wukari",
      "Yorro",
      "Zing",
    ],
  },
  {
    state: "Yobe",
    lgas: [
      "Bade",
      "Bursari",
      "Damaturu",
      "Fika",
      "Fune",
      "Geidam",
      "Gujba",
      "Gulani",
      "Jakusko",
      "Karasuwa",
      "Machina",
      "Nangere",
      "Nguru",
      "Potiskum",
      "Tarmuwa",
      "Yunusari",
      "Yusufari",
    ],
  },
  {
    state: "Zamfara",
    lgas: [
      "Anka",
      "Bakura",
      "Birnin Magaji/Kiyaw",
      "Bukkuyum",
      "Bungudu",
      "Chafe",
      "Gummi",
      "Gusau",
      "Kaura Namoda",
      "Maradun",
      "Maru",
      "Shinkafi",
      "Talata Mafara",
      "Zurmi",
    ],
  },
];

export const Amenities = [
  {
    name: "Air Conditioning",
    icon: "FaSnowflake",
    category: "general",
  },
  {
    name: "Heating",
    icon: "FaFire",
    category: "general",
  },
  {
    name: "Wi-Fi / Internet",
    icon: "FaWifi",
    category: "general",
  },
  {
    name: "Parking",
    icon: "FaParking",
    category: "general",
  },
  {
    name: "Elevator",
    icon: "FaElevator",
    category: "general",
  },
  {
    name: "Laundry (In-Unit)",
    icon: "GiWashingMachine",
    category: "general",
  },
  {
    name: "Laundry (Shared)",
    icon: "GiLaundryMachine",
    category: "general",
  },
  {
    name: "Pet-Friendly",
    icon: "FaDog",
    category: "general",
  },
  {
    name: "Furnished",
    icon: "FaCouch",
    category: "general",
  },
  {
    name: "Wheelchair Accessible",
    icon: "FaWheelchair",
    category: "general",
  },
  {
    name: "Refrigerator",
    icon: "GiFridge",
    category: "kitchen",
  },
  {
    name: "Dishwasher",
    icon: "GiDishwasher",
    category: "kitchen",
  },
  {
    name: "Microwave",
    icon: "GiMicrowave",
    category: "kitchen",
  },
  {
    name: "Oven",
    icon: "GiElectric",
    category: "kitchen",
  },
  {
    name: "Swimming Pool",
    icon: "FaSwimmingPool",
    category: "outdoor",
  },
  {
    name: "Gym / Fitness Center",
    icon: "FaDumbbell",
    category: "outdoor",
  },
  {
    name: "Garden / Yard",
    icon: "FaTree",
    category: "outdoor",
  },
  {
    name: "Balcony / Terrace",
    icon: "MdBalcony",
    category: "outdoor",
  },
  {
    name: "BBQ / Grill Area",
    icon: "GiBarbecue",
    category: "outdoor",
  },
  {
    name: "Playground",
    icon: "GiPlayground",
    category: "outdoor",
  },
  {
    name: "Bike Storage",
    icon: "FaBicycle",
    category: "outdoor",
  },
  {
    name: "Security System",
    icon: "FaShieldAlt",
    category: "security",
  },
  {
    name: "Surveillance Cameras",
    icon: "FaVideo",
    category: "security",
  },
  {
    name: "Fireplace",
    icon: "FaFireplace",
    category: "security",
  },
  {
    name: "Smoke Detectors",
    icon: "MdSmokeFree",
    category: "security",
  },
  {
    name: "Gated Community",
    icon: "FaGate",
    category: "security",
  },
  {
    name: "Smart Home",
    icon: "IoMdSmartphone",
    category: "luxury",
  },
  {
    name: "Concierge Service",
    icon: "FaConciergeBell",
    category: "luxury",
  },
  {
    name: "Spa / Sauna",
    icon: "FaHotTub",
    category: "luxury",
  },
  {
    name: "Cinema / Home Theater",
    icon: "MdMovie",
    category: "luxury",
  },
  {
    name: "Wine Cellar",
    icon: "GiWineBottle",
    category: "luxury",
  },
  {
    name: "Library",
    icon: "FaBook",
    category: "luxury",
  },
  {
    name: "Game Room",
    icon: "GiGamepad",
    category: "luxury",
  },
  {
    name: "Utilities Included",
    icon: "FaPlug",
    category: "utility",
  },
  {
    name: "Water Included",
    icon: "FaTint",
    category: "utility",
  },
  {
    name: "Solar Panels",
    icon: "GiSolarPower",
    category: "utility",
  },
  {
    name: "Electric Car Charging",
    icon: "MdEvStation",
    category: "utility",
  },
  {
    name: "Waste Disposal",
    icon: "GiTrashCan",
    category: "utility",
  },
  {
    name: "Rooftop Deck",
    icon: "MdRoofing",
    category: "community",
  },
  {
    name: "Lounge Area",
    icon: "FaChair",
    category: "community",
  },
  {
    name: "Coworking Space",
    icon: "FaLaptopHouse",
    category: "community",
  },
  {
    name: "Party Room",
    icon: "GiPartyPopper",
    category: "community",
  },
  {
    name: "Near Public Transport",
    icon: "FaBus",
    category: "transport",
  },
  {
    name: "Bike-Friendly",
    icon: "FaBicycle",
    category: "transport",
  },
  {
    name: "Near Highway",
    icon: "FaRoad",
    category: "transport",
  },
];

export const PropertyTypes = [
  // === RESIDENTIAL (Expanded) ===
  { label: "Detached House", value: "detached-house", category: "residential" },
  {
    label: "Semi-Detached House",
    value: "semi-detached",
    category: "residential",
  },
  { label: "Bungalow", value: "bungalow", category: "residential" },
  { label: "Duplex", value: "duplex", category: "residential" },
  { label: "Mansion", value: "mansion", category: "residential" },
  { label: "Apartment (Flat)", value: "apartment", category: "residential" },
  { label: "Penthouse", value: "penthouse", category: "residential" },
  {
    label: "Terraced House (Townhouse)",
    value: "townhouse",
    category: "residential",
  },
  {
    label: "Serviced Apartments",
    value: "serviced-apartments",
    category: "residential",
  },
  {
    label: "Boys' Quarters (BQ)",
    value: "boys-quarters",
    category: "residential",
  },
  {
    label: "Face-Me-I-Face-You",
    value: "face-me-i-face-you",
    category: "residential",
  },
  {
    label: "Gated Community Home",
    value: "gated-community",
    category: "residential",
  },
  { label: "Villa", value: "villa", category: "residential" },
  {
    label: "Beachfront House",
    value: "beachfront-house",
    category: "residential",
  },
  {
    label: "Co-Living Space",
    value: "co-living-space",
    category: "residential",
  },
  {
    label: "Student Housing",
    value: "student-housing",
    category: "residential",
  },
  {
    label: "Elderly Care Home",
    value: "elderly-care-home",
    category: "residential",
  },

  // === COMMERCIAL (Expanded) ===
  { label: "Office Space", value: "office-space", category: "commercial" },
  {
    label: "Co-Working Space",
    value: "co-working-space",
    category: "commercial",
  },
  { label: "Shopping Mall", value: "shopping-mall", category: "commercial" },
  { label: "Retail Shop", value: "retail-shop", category: "commercial" },
  { label: "Supermarket", value: "supermarket", category: "commercial" },
  { label: "Kiosk", value: "kiosk", category: "commercial" },
  { label: "Strip Mall", value: "strip-mall", category: "commercial" },
  {
    label: "Open-Air Market Stall",
    value: "market-stall",
    category: "commercial",
  },
  { label: "Hotel", value: "hotel", category: "commercial" },
  { label: "Guest House", value: "guest-house", category: "commercial" },
  { label: "Event Center", value: "event-center", category: "commercial" },
  { label: "Cinema", value: "cinema", category: "commercial" },
  { label: "Restaurant/Café", value: "restaurant", category: "commercial" },
  { label: "Fuel Station", value: "fuel-station", category: "commercial" },
  {
    label: "Filling Station with Land",
    value: "filling-station",
    category: "commercial",
  },
  {
    label: "Car Dealership Showroom",
    value: "car-showroom",
    category: "commercial",
  },
  { label: "Nightclub/Bar", value: "nightclub", category: "commercial" },
  { label: "Amusement Park", value: "amusement-park", category: "commercial" },
  { label: "Gym/Fitness Center", value: "gym", category: "commercial" },
  { label: "Spa/Wellness Center", value: "spa", category: "commercial" },
  { label: "Land", value: "land", category: "commercial" },

  // === INDUSTRIAL (Expanded) ===
  { label: "Warehouse", value: "warehouse", category: "commercial" },
  { label: "Factory", value: "factory", category: "industrial" },
  {
    label: "Industrial Park",
    value: "industrial-park",
    category: "industrial",
  },
  {
    label: "Cold Storage Facility",
    value: "cold-storage",
    category: "industrial",
  },
  { label: "Tank Farm", value: "tank-farm", category: "industrial" },
  { label: "Logistics Hub", value: "logistics-hub", category: "industrial" },
  {
    label: "Manufacturing Plant",
    value: "manufacturing-plant",
    category: "industrial",
  },
  { label: "Workshop", value: "workshop", category: "industrial" },
  { label: "Bottling Plant", value: "bottling-plant", category: "industrial" },
  { label: "Rice Mill", value: "rice-mill", category: "industrial" },
  { label: "Cement Factory", value: "cement-factory", category: "industrial" },
  { label: "Textile Mill", value: "textile-mill", category: "industrial" },
  {
    label: "Recycling Plant",
    value: "recycling-plant",
    category: "industrial",
  },
  {
    label: "Packaging Facility",
    value: "packaging-facility",
    category: "industrial",
  },

  // === AGRICULTURAL (Expanded) ===
  { label: "Poultry Farm", value: "poultry-farm", category: "agricultural" },
  { label: "Fish Farm", value: "fish-farm", category: "agricultural" },
  { label: "Pig Farm", value: "pig-farm", category: "agricultural" },
  { label: "Cattle Ranch", value: "cattle-ranch", category: "agricultural" },
  {
    label: "Crop Farm (Cassava, Maize, etc.)",
    value: "crop-farm",
    category: "agricultural",
  },
  {
    label: "Plantation (Oil Palm, Rubber, etc.)",
    value: "plantation",
    category: "agricultural",
  },
  {
    label: "Greenhouse Farm",
    value: "greenhouse-farm",
    category: "agricultural",
  },
  {
    label: "Aquaculture Farm",
    value: "aquaculture-farm",
    category: "agricultural",
  },
  {
    label: "Agro-Processing Facility",
    value: "agro-processing",
    category: "agricultural",
  },
  {
    label: "Livestock Market",
    value: "livestock-market",
    category: "agricultural",
  },
  { label: "Feed Mill", value: "feed-mill", category: "agricultural" },

  // === LAND & PLOTS (Expanded) ===
  { label: "Residential Land", value: "residential-land", category: "land" },
  { label: "Commercial Land", value: "commercial-land", category: "land" },
  { label: "Industrial Land", value: "industrial-land", category: "land" },
  { label: "Agricultural Land", value: "agricultural-land", category: "land" },
  { label: "Mixed-Use Land", value: "mixed-use-land", category: "land" },
  { label: "Waterfront Land", value: "waterfront-land", category: "land" },
  {
    label: "Uncompleted Building",
    value: "uncompleted-building",
    category: "land",
  },
  {
    label: "Sand Dredging Site",
    value: "sand-dredging-site",
    category: "land",
  },
  { label: "Quarry Site", value: "quarry-site", category: "land" },
  { label: "Forest Reserve", value: "forest-reserve", category: "land" },

  // === SPECIAL PURPOSE (Expanded) ===
  { label: "Hospital/Clinic", value: "hospital", category: "special-purpose" },
  { label: "School/University", value: "school", category: "special-purpose" },
  {
    label: "Religious Building (Church/Mosque)",
    value: "religious-building",
    category: "special-purpose",
  },
  {
    label: "Government Building",
    value: "government-building",
    category: "special-purpose",
  },
  {
    label: "Military/Police Barracks",
    value: "military-barracks",
    category: "special-purpose",
  },
  {
    label: "Research Facility",
    value: "research-facility",
    category: "special-purpose",
  },
  { label: "Data Center", value: "data-center", category: "special-purpose" },
  {
    label: "Prison/Correctional Facility",
    value: "prison",
    category: "special-purpose",
  },
  { label: "Fire Station", value: "fire-station", category: "special-purpose" },
  {
    label: "Cemetery/Burial Ground",
    value: "cemetery",
    category: "special-purpose",
  },

  // === RECREATIONAL ===
  { label: "Golf Course", value: "golf-course", category: "recreational" },
  {
    label: "Sports Stadium",
    value: "sports-stadium",
    category: "recreational",
  },
  {
    label: "Swimming Pool Complex",
    value: "swimming-pool",
    category: "recreational",
  },
  { label: "Marina (Boat Dock)", value: "marina", category: "recreational" },
  { label: "Game Reserve", value: "game-reserve", category: "recreational" },
  { label: "Park/Green Space", value: "park", category: "recreational" },

  // === INFRASTRUCTURE ===
  { label: "Power Plant", value: "power-plant", category: "infrastructure" },
  {
    label: "Water Treatment Plant",
    value: "water-treatment-plant",
    category: "infrastructure",
  },
  {
    label: "Telecommunication Mast",
    value: "telecom-mast",
    category: "infrastructure",
  },
  {
    label: "Bridge/Tunnel",
    value: "bridge-tunnel",
    category: "infrastructure",
  },
  { label: "Road/Highway", value: "road-highway", category: "infrastructure" },

  // === MISCELLANEOUS ===
  {
    label: "Billboard Advertising Space",
    value: "billboard-space",
    category: "miscellaneous",
  },
  { label: "Parking Lot", value: "parking-lot", category: "miscellaneous" },
  { label: "Storage Unit", value: "storage-unit", category: "miscellaneous" },
  { label: "Solar Farm", value: "solar-farm", category: "miscellaneous" },
  { label: "Wind Farm", value: "wind-farm", category: "miscellaneous" },
];

  export const purposeOptions = [
    { value: "For Rent", label: "For Rent" },
    { value: "Lease", label: "Lease" },
    { value: "For Sale", label: "For Sale" },
    { value: "Shortlet", label: "Shortlet" },
    { value: "Mortgage", label: "Mortgage" },
  ];
export const currencyOptions = [
  { label: "₦", value: "₦",  },
  { label: "£", value: "£",},
  { label: "$", value: "$",  },
  { label: "€", value: "€" }

];


 export const propertySizeOptions = [
  { value: "plot", label: "Plot(s)" },
  { value: "acres", label: "Acres" },
  { value: "sqft", label: "Square Feet (SQFT)" },
  { value: "sqm", label: "Square Meters (SQM)" },
  { value: "hectare", label: "Hectares" },
  { value: "cornerpiece", label: "Corner Piece" },
  { value: "block", label: "Block" },
];

export const propertyDocumentTypes = [
  { value: "c of o", label: "Certificate of Occupancy (C of O)" },
  { value: "governors consent", label: "Governor's Consent" },
  { value: "deed of assignment", label: "Deed of Assignment" },
  { value: "survey plan", label: "Survey Plan" },
  { value: "registered title", label: "Registered Title" },
  { value: "excision and gazette", label: "Excision and Gazette" },
  { value: "deed of gift", label: "Deed of Gift" },
  { value: "deed of lease", label: "Deed of Lease" },
  { value: "deed of mortgage", label: "Deed of Mortgage" },
  { value: "power of attorney", label: "Power of Attorney" },
  { value: "purchase receipt", label: "Purchase Receipt" },
  { value: "approved building plan", label: "Approved Building Plan" },
  { value: "land_use_charge_receipt", label: "Land Use Charge Receipt" },
  { value: "ratification agreement", label: "Ratification Agreement" },
  { value: "contract of sale", label: "Contract of Sale" },
  { value: "allocation letter", label: "Allocation Letter" },
  { value: "development levy receipt", label: "Development Levy Receipt" },
];

export const frequencyOptions = [
  { value: "yearly", label: "Yearly" },
  { value: "monthly", label: "Monthly" },
  { value: "daily", label: "Daily" },
  { value: "hourly", label: "Per Hour" },
  { value: "weekly", label: "Weekly" },
  { value: "outright", label: "Outright Sale" },
  { value: "distress", label: "Distress Sale" },
];

export const professions = [
  // Real Estate Professionals
  { label: "Real Estate Agent", value: "real_estate_agent", role: "realtor" },
  { label: "Broker", value: "broker", role: "realtor" },
  { label: "Property Manager", value: "property_manager", role: "realtor" },
  { label: "Leasing Consultant", value: "leasing_consultant", role: "realtor" },
  {
    label: "Real Estate Developer",
    value: "real_estate_developer",
    role: "realtor",
  },

  // Valuation & Legal
  {
    label: "Property Valuer / Appraiser",
    value: "property_valuer",
    role: "realtor",
  },
  { label: "Real Estate Lawyer", value: "real_estate_lawyer", role: "realtor" },

  // Design & Architecture
  { label: "Architect", value: "architect", role: "service" },
  { label: "Interior Designer", value: "interior_designer", role: "service" },
  {
    label: "Landscape Architect",
    value: "landscape_architect",
    role: "service",
  },
  { label: "Urban Planner", value: "urban_planner", role: "service" },

  // Construction & Engineering
  { label: "Building Engineer", value: "building_engineer", role: "engineer" },
  { label: "Civil Engineer", value: "civil_engineer", role: "engineer" },
  {
    label: "Construction Manager",
    value: "construction_manager",
    role: "engineer",
  },
  { label: "Contractor", value: "contractor", role: "service" },
  { label: "Surveyor", value: "surveyor", role: "service" },

  // Trades & Labor
  { label: "Carpenter", value: "carpenter", role: "service" },
  { label: "Electrician", value: "electrician", role: "service" },
  { label: "Plumber", value: "plumber", role: "service" },
  { label: "Painter", value: "painter", role: "service" },
  { label: "HVAC Technician", value: "hvac_technician", role: "service" },
  { label: "Roofing Contractor", value: "roofing_contractor", role: "service" },

  // Building Materials & Suppliers
  {
    label: "Building Materials Supplier",
    value: "building_materials_supplier",
    role: "trader",
  },
  { label: "Timber Merchant", value: "lumber_merchant", role: "trader" },
  { label: "Tile & Stone Supplier", value: "tile_supplier", role: "trader" },
  {
    label: "Electrical Supplies Dealer",
    value: "electrical_supplier",
    role: "trader",
  },
  {
    label: "Plumbing Supplies Dealer",
    value: "plumbing_supplier",
    role: "trader",
  },
  {
    label: "Paint & Coating Supplier",
    value: "paint_supplier",
    role: "trader",
  },

  // Facility & Maintenance
  { label: "Facility Manager", value: "facility_manager", role: "service" },
  {
    label: "Maintenance Technician",
    value: "maintenance_technician",
    role: "service",
  },
];
export const TitleOptions = [
  { label: "Mr", value: "Mr" },
  { label: "Mrs", value: "Mrs" },
  { label: "Miss", value: "Miss" },
  { label: "Ms", value: "Ms" },
  { label: "Dr", value: "Dr" },
  { label: "Prof", value: "Prof" },
  { label: "Rev", value: "Rev" },
  { label: "Chief", value: "Chief" },

];

